### ISSUE TITLE
Timestamp issues

### ISSUE THREAD

**Issue by ashamvenu** [DataResponsibly/DataSynthesizer#36]
* DataSynthesizer version: DataSynthesizer-0.1.10-py2.py3-none-any.whl (24 kB)
* Python version: Python 3.7.6
* Operating System: Windows 10

### Description

Hello,

I am trying to generate synthetic data where one column comprises timestamp.

### What I Did

 I am using random mode. Everything seems fine. The program throws no errors. But the timestamps are generated in float.

```
INPUT:

timestamp
--
17-10-1999
13-12-1999
22-03-2000
23-03-2000
25-03-2000
05-05-2000
15-05-2000
23-05-2000

OUTPUT:
timestamp
--
84.53577
53.62745
68.02702
60.91776
9.8478
9.202759
5.596583
8.653249


```

**Comment by haoyueping** [comment]
Thanks for your feedback! The DateTime format is not well handled due to issues like different date formats, dates vs timestamps, etc. DataSynthesizer fundamentally regards DateTime values as floats even for date values. So you can manually convert the output timestamps into any date format as a post-process step. Another approach to avoid this DateTime issue is to split this column into three columns: Day, Month, Year. Then merge them into one column after running DataSynthesizer, again as a post-process step.

W.r.t. the random mode only generates float numbers between 0 and 100, this is due to the Differential Privacy concern to hide the real range of values for the numerical attributes. If you really only need random mode, you can certainly just use the 2nd approach above, splitting the column into three.

Hope it helps.

**Comment by ashamvenu** [comment]
Thanks for your response. I have solved it by generating the timestamp column separately as a post-process.
